const pageSectionsText = [
  {
    id: '1',
    type: 'text',
    imgPath: 'static/assets/product-1.png',
    backgroundColor: 'offWhite',
    title: 'Why do I need an Orthodontist?',
    body: 'There’s a lot of factors that go into moving your teeth around in your mouth, and it’s never one-size-fits-all. All Smile Lounge Orthodontists have undergone four years of specialized training to ensure effective and safe alignment, and will monitor your smile progress throughout your entire treatment. We don’t drop a box of aligners off on your doorstep and disappear, we finetune your alignments so your smile is not only perfect, but healthy.',
  },
  {
    id: '2',
    type: 'text/image',
    side: 'left',
    backgroundColor: 'coral',
    title: 'Consultation',
    imgPath: 'static/assets/consultation.png',
    body: 'At your first appointment you and your Orthodontist will discuss your smile goals and determine if you qualify for invisible aligners. We’ll take a 3D scan of your teeth, and your Orthodontist will design your custom aligners based on your bespoke treatment plan. We are conveniently located in coworking spaces across New York City.',
  },
  {
    id: '3',
    type: 'text/image',
    side: 'right',
    backgroundColor: 'peach',
    imgPath: 'static/assets/treatment.png',
    title: 'Treatment',
    body: 'Once your aligners are ready you’ll meet with your Orthodontist to ensure they fit perfectly (all of our aligners are made locally in Brooklyn!), and we’ll perform any oral maintenance, like buttons or shaping, if needed. You’ll then receive subsequent aligners every 3 months, sent directly to your doorstep. Throughout your treatment you’ll meet with your Orthodontist virtually, every 6 weeks, to ensure your teeth are aligning correctly and healthy!',
  },
  {
    id: '4',
    type: 'text/image',
    side: 'left',
    backgroundColor: 'aqua',
    imgPath: 'static/assets/success.png',
    title: 'Success!',
    body: 'Once you’ve reached your goals, your Orthodontist will clean, polish, and smooth out your new smile. You’ll also receive custom retainers, so you can maintain the results you’ve created.',
  },
  {
    id: '5',
    type: 'text',
    textColor: 'offWhite',
    backgroundColor: 'darkGreen',
    title: 'Put your smile in the hands of a professional',
  },
  {
    id: '6',
    type: 'text/image',
    side: 'left',
    backgroundColor: 'offWhite',
    imgPath: 'static/assets/why-choose.png',
    title: 'Why Choose Smile Lounge?',
    body: 'We know nowadays that there are a handful of companies that provide custom made invisible aligners, so it can be hard to choose. At Smile Lounge, we believe that the convenience gained from having patients perform their own impressions and track their own progress falls short of the expertise provided by a trained Orthodontist. Our Orthodontists have undergone extensive training in tooth alignment, health, and understanding what exactly makes a beautiful smile – because it’s not always as simple as straightening your teeth. Smile Lounge is the only alignment company where specialty trained Orthodontists monitor you along every step of the way.',
  },
  {
    id: '7',
    type: 'text',
    backgroundColor: 'coral',
    title: 'Expert Testimonials',
    body: 'OFFICI BEATURE PERSPE PA VOLORIOSTRUM HARIO. FICILLO RERATIIS EROVIDUS SIT SOLUPTA TEMPOREM VOLUPTIUM SITIO.',
  },
];

export default pageSectionsText;
